
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 07 11:04:57 EDT 2012
//----------------------------------------------------

package constraint.parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 14;
  public static final int STAR = 10;
  public static final int EOF = 0;
  public static final int EQ = 3;
  public static final int ARROW = 7;
  public static final int CONSTRACTOR = 2;
  public static final int error = 1;
  public static final int AT = 11;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 6;
  public static final int IDENTIFIER = 13;
  public static final int LPAREN = 8;
  public static final int GEQ = 5;
  public static final int INTEGER_LITERAL = 12;
  public static final int LEQ = 4;
}

