env:
 - GHCVER=6.12.3
 - GHCVER=7.0.1
 - GHCVER=7.0.2
 - GHCVER=7.0.3
 - GHCVER=7.0.4
 - GHCVER=7.2.1
 - GHCVER=7.2.2
 - GHCVER=7.4.1
 - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
 - if [ "$GHCVER" = "6.12.3" ]; then
      cabal-1.18 install --only-dependencies;
      cabal-1.18 install 'QuickCheck==2.6.*';
   else
      cabal-1.18 install --only-dependencies --enable-tests;
   fi

script:
 - cd tests/ && runghc ./GenTests.hs && cd ..
 - cabal-1.18 configure --enable-tests -v2
 - cabal-1.18 build
 - cabal-1.18 test
 - cabal-1.18 check
 - cabal-1.18 sdist
