(* # generated by ./configure -prefix /home/zhdf/easyocaml-0.49/ocaml-3.10.2 *)
let prefix = "/home/zhdf/easyocaml-0.49/ocaml-3.10.2";;
let bindir = prefix^"/bin";;
let libdir = prefix^"/lib/ocaml";;
let stublibdir = libdir^"/stublibs";;
let mandir = prefix^"/man";;
let manext = "1";;
let ranlib = "ranlib";;
let ranlibcmd = "ranlib";;
let sharpbangscripts = true;;
let bng_arch = "ia32";;
let bng_asm_level = "2";;
let pthread_link = "-cclib -lpthread";;
let x11_includes = "";;
let x11_link = "not found";;
let dbm_includes = "not found";;
let dbm_link = "not found";;
let tk_defs = "";;
let tk_link = "";;
let bytecc = "gcc";;
let bytecccompopts = "-fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT";;
let bytecclinkopts = " -Wl,-E";;
let bytecclibs = " -lm  -ldl -lcurses -lpthread";;
let byteccrpath = "-Wl,-rpath,";;
let exe = "";;
let supports_shared_libraries = true;;
let sharedcccompopts = "-fPIC";;
let mksharedlibrpath = "-Wl,-rpath,";;
(* SYSLIB=-l"^1^" *)
let syslib x = "-l"^x;;

(* MKEXE="^bytecc^" -o "^1^" "^2^" *)
let mkexe out files opts = Printf.sprintf "%s -o %s %s %s" bytecc out opts files;;

(* ### How to build a DLL *)
(* MKDLL=gcc -shared -o "^1^" "^3^" *)
let mkdll out _implib files opts = Printf.sprintf "%s %s %s %s" "gcc -shared -o" out opts files;;

(* ### How to build a static library *)
(* MKLIB=ar rc "^1^" "^2^"; ranlib "^1^" *)
let mklib out files opts = Printf.sprintf "ar rc %s %s %s; ranlib %s" out opts files out;;
let arch = "i386";;
let model = "default";;
let system = "linux_elf";;
let nativecc = "gcc";;
let nativecccompopts = "-Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT";;
let nativeccprofopts = "-Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT";;
let nativecclinkopts = "";;
let nativeccrpath = "-Wl,-rpath,";;
let nativecclibs = " -lm  -ldl";;
let asflags = "";;
let aspp = "gcc";;
let asppflags = "-c -DSYS_"^system;;
let asppprofflags = "-DPROFILING";;
let profiling = "prof";;
let dynlinkopts = " -ldl";;
let otherlibraries = "unix str num dynlink bigarray systhreads threads";;
let debugger = "ocamldebugger";;
let cc_profile = "-pg";;
let systhread_support = true;;
let partialld = "ld -r";;
let dllcccompopts = "";;
let o = "o";;
let a = "a";;
let ext_obj = ".o";;
let ext_asm = ".s";;
let ext_lib = ".a";;
let ext_dll = ".so";;
let extralibs = "";;
let ccomptype = "cc";;
let toolchain = "cc";;
