#!/bin/sh
dir=/usr/local/www/research/SHErrLoc

if [[ -r shipit.local ]]
then
    . shipit.local
fi

if [[ -z "$WEBHOST" ]]
then
    WEBHOST=cslinux
fi
if [[ -z "$real_web" ]]
then
    real_web=$USER@$WEBHOST:$dir
fi
svn update
rsync "$@" -truvlC --exclude '*.cfg'					      \
              --exclude Makefile					      \
              --exclude '.*.swp'					      \
              --exclude '.*.swo'					      \
              --exclude shipit 						      \
	      --exclude '.nfs*'						      \
              --exclude '*~'						      \
              --exclude '.*'						      \
    ./ "$real_web"/
